name: Gatsby Build and Deploy to GitHub Pages on Push

on:
push:
  branches:
    - master
jobs:
build-and-deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: pooyagolchian/pooyagolchian.github.io@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: develop
        FOLDER: public
        BUILD_SCRIPT: npm install && npm run build
