name: Gatsby Publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pooyagolchian/pooyagolchian.github.io@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
