on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@develop
      - run: npm install;npm run build
      - name: Deploy
        uses: pooyagolchian/pooyagolchian.github.io@develop
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public
          publish_branch: master
